import { Router } from 'express';
import { healthRoutes } from './health.routes.js';
import { authRoutes } from '../modules/auth/auth.routes.js';
import { userRoutes } from '../modules/users/user.routes.js';
import { productRoutes } from '../modules/products/product.routes.js';
import { pricelistRoutes } from '../modules/pricelists/pricelist.routes.js';
import { discountTierRoutes } from '../modules/discount-tiers/discount-tier.routes.js';
import { warehouseRoutes } from '../modules/warehouses/warehouse.routes.js';
import { quotationRoutes } from '../modules/quotations/quotation.routes.js';
export const routes = Router();
routes.use(healthRoutes);
routes.use('/auth', authRoutes);
routes.use('/users', userRoutes);
routes.use('/products', productRoutes);
routes.use('/pricelists', pricelistRoutes);
routes.use('/discount-tiers', discountTierRoutes);
routes.use('/warehouses', warehouseRoutes);
routes.use('/quotations', quotationRoutes);
